[Icon Theme]
Name=Monolith
Comment=Monochrome folder icons
Example=folder
Inherits=Adwaita,hicolor
Directories=scalable/places,scalable/mimetypes,scalable/status

[scalable/places]
Context=Places
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Context=MimeTypes
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/status]
Context=Status
Size=128
MinSize=8
MaxSize=512
Type=Scalable
